name: pokedex_clean
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  dartz: ^0.10.1
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  go_router: ^14.1.4
  internet_connection_checker: ^1.0.0+1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  palette_generator: ^0.3.3+3
  path_provider: ^2.1.3
  responsive_framework: ^1.4.0
  animate_do: ^3.3.4
  flutter_native_splash: ^2.4.0
  url_launcher: ^6.3.0
  

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/
